---

# CIS benchmark 2.4.1.2
# Wazuh configuration assessment ID: 35594
# Ensure permissions on /etc/crontab are configured
#
# obtained from
# - https://downloads.cisecurity.org/#/
# - https://learn.cisecurity.org/l/799323/2025-06-10/4vddgt
#   - section 2.4.1.2

- name: "2.4.1.2: Ensure permissions on /etc/crontab are configured"
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: "600"
  become: true
  when:
    - ansible_os_family == "Debian"
    - inventory_hostname in groups["wazuh_agent"]
  notify:
    - restart-wazuh-agent
