---

# CIS benchmark 5.1.20
# Wazuh configuration assessment ID: 35659
# disable Root login via SSH
#
# obtained from
# - https://downloads.cisecurity.org/#/
# - https://learn.cisecurity.org/l/799323/2025-06-10/4vddgt
#   - section 5.1.20

- name: "Disable root SSH login"
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    append_newline: true
    prepend_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK: disable root SSH login"
    block: PermitRootLogin no
    validate: sshd -T -f %s
  become: true
  when:
    - ansible_os_family == "Debian"
    - inventory_hostname in groups["wazuh_agents"]

- name: "Restart sshd"
  ansible.builtin.systemd_service:
    name: sshd
    state: restarted
  become: true

- name: "Restart wazuh agent"
  ansible.builtin.systemd_service:
    name: wazuh-agent
    state: restarted
  become: true
