---

# CIS benchmark 5.1.1
# Wazuh configuration assessment ID: 35640
# Set correct file permissions on /etc/ssh/sshd_config
#
# obtained from
# - https://downloads.cisecurity.org/#/
# - https://learn.cisecurity.org/l/799323/2025-06-10/4vddgt
#   - section 5.1.1

- name: "5.1.1: Set /etc/ssh/sshd_config file permission to 600"
  ansible.builtin.file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "600"
  become: true
  when:
    - ansible_os_family == "Debian"
    - inventory_hostname in groups["wazuh_agent"]
  notify:
    - restart-sshd
    - restart-wazuh-agent
